---
- hosts: all
  become: yes
  gather_facts: False

  tasks:
    - name: Instala git
      apt: pkg=git state=present

    - name: Instalar pip3
      apt:
        package: python3-pip
        state: latest

    - name: Instalar pip
      apt:
        package: python-pip
        state: latest

    - name: Clonar repositorio
      become: false
      git:
        repo: https://github.com/Gecofer/proyecto-CC.git
        dest: proyecto-CC

    - name: Instalando dependencias del proyecto
      pip:
        requirements: /home/gemazure-francecentre/proyecto-CC/requirements.txt
        executable: pip3
